<?php
/**
 * @file
 * Description here.
 */

/**
 * hook_menu
 */
function scoutis_menu() {
  $items = array();
  $items['/admin/config/scoutis'] = array(
    'title' => 'scoutis config',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('scoutis_config'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'scoutis.admin.inc',
  );

  // return $items;
}
